services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: DATABASE_URL
        sync: false

      - key: ADMIN_ID
        value: "6697338101"

      - key: SYRIATEL_CASH
        value: "77178326"

      - key: REFERRAL_REWARD
        value: "1000"

      - key: MIN_WITHDRAW
        value: "15000"

      - key: PORT
        value: "10000"
